name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build and test
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            auth_service
      - name: pytest
        run: |
          docker run -d --name postgres -p 5455:5432 -e POSTGRES_USER=postgresUser -e POSTGRES_PASSWORD=postgresPW -e POSTGRES_DB=postgresDB -d postgres
          sleep 40
          alembic revision --autogenerate -m 'Initial migration'
          alembic upgrade head
          uvicorn main:app
          pytest -v

