name: Test

env:
    TEST: 'test'

on:
  push:
    branches: [TEST]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: test
        run: |
          docker run -d -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.11-management
          sleep 30
          gunicorn -D -b 127.0.0.1:8000 -w 4 -k uvicorn.workers.UvicornWorker main:app
          pytest tests/test_users.py
