name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Build and test
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            auth_service:latest
      - name: pytest
        run: |
          docker run -p 8000:8000 -d auth:latest
          sleep 30
          pytest

