name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: test
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000
          pytest
          
      # - name: Build and test
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: false
      #     tags: |
      #       auth_service:dev
      # - name: pytest
      #   run: |
      #     alembic init alembic
      #     docker run -p 8000:8000 -d auth_service:dev
      #     sleep 30
      #     pytest

